### ISSUE TITLE
Issue on start ATT Archlinux Arcris

### ISSUE THREAD

**Issue by eXoRTH** [arcolinux/archlinux-tweak-tool#11]
Hi, i've a trouble with ArchLinux Tweak Tool, somebody help me?
i try start the ATT and appear this error in terminal:

---------------------------------------------------------------------------
[INFO] : pkgver = pkgversion
[INFO] : pkgrel = pkgrelease
---------------------------------------------------------------------------
[INFO] : Distro = arch
---------------------------------------------------------------------------
Traceback (most recent call last):
 File "/usr/share/archlinux-tweak-tool/archlinux-tweak-tool.py", line 4593, in <module>
   w = Main()
       ^^^^^^
 File "/usr/share/archlinux-tweak-tool/archlinux-tweak-tool.py", line 690, in __init__
   gui.gui(self, Gtk, Gdk, GdkPixbuf, base_dir, os, Pango)
 File "/usr/share/archlinux-tweak-tool/gui.py", line 171, in gui
   fixes_gui.gui(self, Gtk, vboxstack19, fn, fixes)
 File "/usr/share/archlinux-tweak-tool/fixes_gui.py", line 143, in gui
   self.parallel_downloads.set_active(act_number)
TypeError: Argument 1 does not allow None as a value

thank you!

PD: Sorry for my English!

**Comment by Sridal** [comment]
I've had something similar 
```
Traceback (most recent call last):
  File "/usr/share/archlinux-tweak-tool/archlinux-tweak-tool.py", line 4623, in <module>
    w = Main()
        ^^^^^^
  File "/usr/share/archlinux-tweak-tool/archlinux-tweak-tool.py", line 651, in __init__
    gui.gui(self, Gtk, Gdk, GdkPixbuf, base_dir, os, Pango)
  File "/usr/share/archlinux-tweak-tool/gui.py", line 190, in gui
    neofetch_gui.gui(self, Gtk, vboxstack8, neofetch, fn)
  File "/usr/share/archlinux-tweak-tool/neofetch_gui.py", line 147, in gui
    neofetch.get_checkboxes(self)
  File "/usr/share/archlinux-tweak-tool/neofetch.py", line 237, in get_checkboxes
    if "on" in line[0]:
               ~~~~^^^
IndexError: list index out of range
```

**Comment by arcolinuxz** [comment]
Give us a probe link please

**Comment by arcolinuxz** [comment]
See that you have our arcolinux  neofetch config

**Comment by Sridal** [comment]
I found out what the issue was, I had heavily customized my neofetch config removing most of the unnecessary lines which cause the tweak tool to spit out the error. I had found this some time ago but forgot to mention it here.
