### ISSUE TITLE
Fails to start - list index out of range

### ISSUE THREAD

**Issue by madewithpat** [arcolinux/archlinux-tweak-tool#2]
Fresh install of Arcolinux v 22.06.07, att fails to launch

```
Traceback (most recent call last):
  File "/usr/share/archlinux-tweak-tool/archlinux-tweak-tool.py", line 3258, in <module>
    w = Main()
  File "/usr/share/archlinux-tweak-tool/archlinux-tweak-tool.py", line 469, in __init__
    GUI.GUI(self, Gtk, Gdk, GdkPixbuf, base_dir, os, Pango)
  File "/usr/share/archlinux-tweak-tool/GUI.py", line 169, in GUI
    Login_GUI.GUI(self, Gtk, GdkPixbuf, vboxStack22, sddm, lightdm, os, Functions)
  File "/usr/share/archlinux-tweak-tool/Login_GUI.py", line 137, in GUI
    sddm.pop_cursor_box(self, self.cbt_cursor_themes)
  File "/usr/share/archlinux-tweak-tool/sddm.py", line 177, in pop_cursor_box
    name = check_sddm(lines, "CursorTheme=").split("=")[1]
  File "/usr/share/archlinux-tweak-tool/sddm.py", line 57, in check_sddm
    pos = Functions._get_position(lists, value)
  File "/usr/share/archlinux-tweak-tool/Functions.py", line 186, in _get_position
    position = lists.index(data[0])
IndexError: list index out of range
```

**Comment by TommyAGK** [comment]
hey man, I wrote a fix for this, hopefully it gets merged soon.
If you cant wait, check out the pull request and make the changes locally for yourself.
